### PR TITLE
Upgrade to Elm 0.18

### PR DESCRIPTION
**Pull request by newlandsvalley**
And also add a little more of the original haskell functions ported to Elm

### CODE REVIEW

**Comment by danigb** [comment]
Hi John, I've been thinking lately to return to this again. Great you did it! I will too! It seems that this pull request ha some conflicts. I will take a look.

**Comment by newlandsvalley** [comment]
I can't understand why we have merge conflicts - I'm the only one who's changing anything!

**Comment by danigb** [comment]
Yes, I get a lot of conflicts... I can't undestand why...

**Comment by danigb** [comment]
Probably it's better you resolve them, because they are scattered all inside the code and maybe I break anything...

**Comment by newlandsvalley** [comment]
OK - I was under the impression that all my development was in my own fork.  Looks to me as if with the very first edit 'Add some MoreMusic and upgradec to latest elm-test ' I must have somehow stupidly updated both repositories directly with some of this code.  In which case, we should be OK to take everything from the PR.  I'll have a good look later on when I get a bit of time.

**Pull request merged**
